In [1]:
import numpy as np
import pandas as pd

In [ ]:
### Here while importing the data, it could have data in certain lines that cannot be imported so such data causes the 
# importing process to halt. So, to prevent such problems, we use on_bad_lines 

In [6]:
books = pd.read_csv('Books.csv', sep=',', on_bad_lines='skip', encoding='latin-1')

C:\Users\Vision\AppData\Local\Temp\ipykernel_1120\1530214702.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv', sep=',', on_bad_lines='skip', encoding='latin-1')


In [7]:
books.head()

ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author Year-Of-Publication                   Publisher  \
0    Mark P. O. Morford                2002     Oxford University Press   
1  Richard Bruce Wright                2001       HarperFlamingo Canada   
2          Carlo D'Este                1991             HarperPerennial   
3      Gina Bari Kolata                1999        Farrar Straus Giroux   
4       E. J. W. Barber                1999  W. W. Norton &amp; Company   

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

In [10]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [11]:
books = books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher']]

In [12]:
books.head()

ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author Year-Of-Publication                   Publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [13]:
books.rename(columns={'Book-Title':'title', 'Book-Author':'author', 'Year-Of-Publication':'year', 'Publisher':'publisher'}, inplace=True)

C:\Users\Vision\AppData\Local\Temp\ipykernel_1120\3015659066.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books.rename(columns={'Book-Title':'title', 'Book-Author':'author', 'Year-Of-Publication':'year', 'Publisher':'publisher'}, inplace=True)


In [14]:
books.head()

ISBN                                              title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

                 author  year                   publisher  
0    Mark P. O. Morford  2002     Oxford University Press  
1  Richard Bruce Wright  2001       HarperFlamingo Canada  
2          Carlo D'Este  1991             HarperPerennial  
3      Gina Bari Kolata  1999        Farrar Straus Giroux  
4       E. J. W. Barber  1999  W. W. Norton &amp; Company

In [24]:
users=pd.read_csv('Users.csv', on_bad_lines='skip', encoding='latin-1')

In [25]:
users.head()

User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [26]:
users.rename(columns={'User-ID':'user-id', 'Location':'location', 'Age':'age'}, inplace=True)

In [27]:
users.head()

user-id                            location   age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [28]:
ratings=pd.read_csv('Ratings.csv', on_bad_lines='skip', encoding='latin-1')

In [29]:
ratings.head(2)

User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [31]:
ratings.rename(columns={'User-ID':'user-id', 'Book-Rating':'rating'}, inplace=True)

In [32]:
ratings.head()

user-id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [35]:
books.shape

(271360, 5)

In [36]:
users.shape

(278858, 3)

In [37]:
ratings.shape

(1149780, 3)

In [38]:
# To make the model effective, we limit the number of users and books. By doing so only the credible users are selected who
# have given lots of reviews and also we select only those books which have been read by lots of users.

In [39]:
# First we find which user has given how many ratings
ratings['user-id'].value_counts()

user-id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...  
116180        1
116166        1
116154        1
116137        1
276723        1
Name: count, Length: 105283, dtype: int64

In [40]:
ratings['user-id'].value_counts()>200

user-id
11676      True
198711     True
153662     True
98391      True
35859      True
          ...  
116180    False
116166    False
116154    False
116137    False
276723    False
Name: count, Length: 105283, dtype: bool

In [41]:
x=ratings['user-id'].value_counts()>200

In [44]:
# To find only true values from x, we send x inside x
x[x]

user-id
11676     True
198711    True
153662    True
98391     True
35859     True
          ... 
274808    True
28634     True
59727     True
268622    True
188951    True
Name: count, Length: 899, dtype: bool

In [46]:
y=x[x]

In [47]:
y.shape

(899,)

In [48]:
y

user-id
11676     True
198711    True
153662    True
98391     True
35859     True
          ... 
274808    True
28634     True
59727     True
268622    True
188951    True
Name: count, Length: 899, dtype: bool

In [49]:
y=x[x].index

In [50]:
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,  73681,  44296, 155916,   9856, 274808,  28634,  59727, 268622,
       188951],
      dtype='int64', name='user-id', length=899)

In [51]:
ratings['user-id'].isin(y)

0          False
1          False
2          False
3          False
4          False
           ...  
1149775    False
1149776    False
1149777    False
1149778    False
1149779    False
Name: user-id, Length: 1149780, dtype: bool

In [52]:
ratings[ratings['user-id'].isin(y)]

user-id        ISBN  rating
1456      277427  002542730X      10
1457      277427  0026217457       0
1458      277427  003008685X       8
1459      277427  0030615321       0
1460      277427  0060002050       0
...          ...         ...     ...
1147612   275970  3829021860       0
1147613   275970  4770019572       0
1147614   275970   896086097       0
1147615   275970  9626340762       8
1147616   275970  9626344990       0

[526356 rows x 3 columns]

In [53]:
ratings=ratings[ratings['user-id'].isin(y)]

In [54]:
ratings.shape

(526356, 3)

In [55]:
ratings.head()

user-id        ISBN  rating
1456   277427  002542730X      10
1457   277427  0026217457       0
1458   277427  003008685X       8
1459   277427  0030615321       0
1460   277427  0060002050       0

In [56]:
ratings_with_books=ratings.merge(books, on='ISBN')

In [61]:
ratings_with_books.head()

user-id        ISBN  rating  \
0   277427  002542730X      10   
1     3363  002542730X       0   
2    11676  002542730X       6   
3    12538  002542730X      10   
4    13552  002542730X       0   

                                               title             author  year  \
0  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
1  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
2  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
3  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
4  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   

                   publisher  
0  John Wiley &amp; Sons Inc  
1  John Wiley &amp; Sons Inc  
2  John Wiley &amp; Sons Inc  
3  John Wiley &amp; Sons Inc  
4  John Wiley &amp; Sons Inc

In [60]:
ratings_with_books.shape

(487671, 7)

In [59]:
# Here, we can see that the number of rows decreased which is because some of the books in ratings df are not present in
# the books df.

In [63]:
ratings_with_books.groupby('title')['rating'].count()

title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    2
 Always Have Popsicles                                                                                        1
 Apple Magic (The Collector's series)                                                                         1
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   1
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                1
                                                                                                             ..
Ã?Â?ber die Pflicht zum Ungehorsam gegen den Staat.                                                         3
Ã?Â?lpiraten.                                                                                               1
Ã?Â?rger mit Produkt X. Roman.                                                                  

In [65]:
number_rating=ratings_with_books.groupby('title')['rating'].count().reset_index()

In [66]:
number_rating.head()

title  rating
0   A Light in the Storm: The Civil War Diary of ...       2
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Beyond IBM: Leadership Marketing and Finance ...       1
4   Clifford Visita El Hospital (Clifford El Gran...       1

In [67]:
number_rating.rename(columns={'rating':'number of ratings'}, inplace=True)

In [68]:
number_rating.head()

title  number of ratings
0   A Light in the Storm: The Civil War Diary of ...                  2
1                              Always Have Popsicles                  1
2               Apple Magic (The Collector's series)                  1
3   Beyond IBM: Leadership Marketing and Finance ...                  1
4   Clifford Visita El Hospital (Clifford El Gran...                  1

In [69]:
number_rating.shape

(160269, 2)

In [70]:
final_rating=ratings_with_books.merge(number_rating, on='title')

In [71]:
final_rating.head()

user-id        ISBN  rating  \
0   277427  002542730X      10   
1     3363  002542730X       0   
2    11676  002542730X       6   
3    12538  002542730X      10   
4    13552  002542730X       0   

                                               title             author  year  \
0  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
1  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
2  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
3  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
4  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   

                   publisher  number of ratings  
0  John Wiley &amp; Sons Inc                 82  
1  John Wiley &amp; Sons Inc                 82  
2  John Wiley &amp; Sons Inc                 82  
3  John Wiley &amp; Sons Inc                 82  
4  John Wiley &amp; Sons Inc                 82

In [72]:
final_rating.shape

(487671, 8)

In [74]:
final_rating['number of ratings']>=50

0          True
1          True
2          True
3          True
4          True
          ...  
487666    False
487667    False
487668    False
487669    False
487670    False
Name: number of ratings, Length: 487671, dtype: bool

In [76]:
final_rating=final_rating[final_rating['number of ratings']>=50]

In [77]:
final_rating.head()

user-id        ISBN  rating  \
0   277427  002542730X      10   
1     3363  002542730X       0   
2    11676  002542730X       6   
3    12538  002542730X      10   
4    13552  002542730X       0   

                                               title             author  year  \
0  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
1  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
2  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
3  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
4  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   

                   publisher  number of ratings  
0  John Wiley &amp; Sons Inc                 82  
1  John Wiley &amp; Sons Inc                 82  
2  John Wiley &amp; Sons Inc                 82  
3  John Wiley &amp; Sons Inc                 82  
4  John Wiley &amp; Sons Inc                 82

In [78]:
final_rating.shape

(61853, 8)

- Here, the rows having same user with same books need to removed which is done by drop_duplicates which drops rows having 
  same user and same book title.

In [80]:
final_rating.drop_duplicates(['user-id', 'title'], inplace=True)

C:\Users\Vision\AppData\Local\Temp\ipykernel_1120\143881038.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_rating.drop_duplicates(['user-id', 'title'], inplace=True)


In [81]:
final_rating.head()

user-id        ISBN  rating  \
0   277427  002542730X      10   
1     3363  002542730X       0   
2    11676  002542730X       6   
3    12538  002542730X      10   
4    13552  002542730X       0   

                                               title             author  year  \
0  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
1  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
2  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
3  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
4  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   

                   publisher  number of ratings  
0  John Wiley &amp; Sons Inc                 82  
1  John Wiley &amp; Sons Inc                 82  
2  John Wiley &amp; Sons Inc                 82  
3  John Wiley &amp; Sons Inc                 82  
4  John Wiley &amp; Sons Inc                 82

- Now we create a pivot table with users in columns, books in rows and ratings are the values of the table

In [87]:
book_pivot=final_rating.pivot_table(columns='user-id', index='title', values='rating')

In [88]:
book_pivot.head()

user-id                254     2276    2766    2977    3363    3757    4017    \
title                                                                           
1984                      9.0     NaN     NaN     NaN     NaN     NaN     NaN   
1st to Die: A Novel       NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2nd Chance                NaN    10.0     NaN     NaN     NaN     NaN     NaN   
4 Blondes                 NaN     NaN     NaN     NaN     NaN     NaN     NaN   
84 Charing Cross Road     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

user-id                4385    6242    6251    ...  274004  274061  274301  \
title                                          ...                           
1984                      NaN     NaN     NaN  ...     NaN     NaN     NaN   
1st to Die: A Novel       NaN     NaN     NaN  ...     NaN     NaN     NaN   
2nd Chance                NaN     NaN     NaN  ...     NaN     NaN     NaN   
4 Blondes                 NaN     NaN     0.0  ...     NaN     NaN     NaN   
84 Charing Cross Road     NaN     NaN     NaN  ...     NaN     NaN     NaN   

user-id                274308  274808  275970  277427  277478  277639  278418  
title                                                                          
1984                      NaN     NaN     0.0     NaN     NaN     NaN     NaN  
1st to Die: A Novel       NaN     NaN     NaN     NaN     NaN     NaN     NaN  
2nd Chance                0.0     NaN     NaN     NaN     NaN     0.0     NaN  
4 Blondes                 NaN     NaN     NaN     NaN     NaN     NaN     NaN  
84 Charing Cross Road     NaN     NaN    10.0     NaN     NaN     NaN     NaN  

[5 rows x 888 columns]

In [89]:
book_pivot.shape

(742, 888)

In [90]:
book_pivot.fillna(0, inplace=True)

In [91]:
book_pivot.head()

user-id                254     2276    2766    2977    3363    3757    4017    \
title                                                                           
1984                      9.0     0.0     0.0     0.0     0.0     0.0     0.0   
1st to Die: A Novel       0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2nd Chance                0.0    10.0     0.0     0.0     0.0     0.0     0.0   
4 Blondes                 0.0     0.0     0.0     0.0     0.0     0.0     0.0   
84 Charing Cross Road     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

user-id                4385    6242    6251    ...  274004  274061  274301  \
title                                          ...                           
1984                      0.0     0.0     0.0  ...     0.0     0.0     0.0   
1st to Die: A Novel       0.0     0.0     0.0  ...     0.0     0.0     0.0   
2nd Chance                0.0     0.0     0.0  ...     0.0     0.0     0.0   
4 Blondes                 0.0     0.0     0.0  ...     0.0     0.0     0.0   
84 Charing Cross Road     0.0     0.0     0.0  ...     0.0     0.0     0.0   

user-id                274308  274808  275970  277427  277478  277639  278418  
title                                                                          
1984                      0.0     0.0     0.0     0.0     0.0     0.0     0.0  
1st to Die: A Novel       0.0     0.0     0.0     0.0     0.0     0.0     0.0  
2nd Chance                0.0     0.0     0.0     0.0     0.0     0.0     0.0  
4 Blondes                 0.0     0.0     0.0     0.0     0.0     0.0     0.0  
84 Charing Cross Road     0.0     0.0    10.0     0.0     0.0     0.0     0.0  

[5 rows x 888 columns]

- Now we use clustering algorithm to group the closest elements on the basis of distance which is done using nearest 
  neighbour. Here, instead of calculating all the distances, we can skip the distance calculation for 0 values using the 
  sparse matrix. On doing so, it only calculates the non zero distances.

In [94]:
from scipy.sparse import csr_matrix
book_sparse=csr_matrix(book_pivot)

In [95]:
type(book_sparse)

scipy.sparse._csr.csr_matrix

-  Here, we use brute method in other to calculate the distance for all non-zero elements. By default, it doesnot calculate the distances for all elements and it skips for some elements based on its own understanding.

In [97]:
from sklearn.neighbors import NearestNeighbors
model=NearestNeighbors(algorithm='brute')

In [98]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

- This models gives output as distances, suggestions and for the prediction, we need to pass the whole row of a book i.e all the columns of a specific book. reshape(1,-1) is used to reshape the output into a 2D format with shape (1,N) where N is the number of columns which is automatically inferred as seen in the outputs of distances and suggestions given below.

In [102]:
distances, suggestions=model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1), n_neighbors=6)

In [103]:
distances

array([[ 0.        , 68.78953409, 69.5413546 , 72.64296249, 76.83098333,
        77.28518616]])

In [104]:
suggestions

array([[237, 240, 238, 241, 184, 536]], dtype=int64)

In [105]:
for i in range(len(suggestions)):
    print(book_pivot.index[suggestions[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall'],
      dtype='object', name='title')


In [106]:
book_pivot.index

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='title', length=742)

In [107]:
book_pivot.index[237]

'Harry Potter and the Chamber of Secrets (Book 2)'

In [108]:
book_pivot.index[54]

'Animal Farm'

In [109]:
book_pivot.index=='Animal Farm'

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [110]:
# we need to extract the true value for this we can use:
np.where(book_pivot.index=='Animal Farm')

(array([54], dtype=int64),)

In [112]:
np.where(book_pivot.index=='Animal Farm')[0][0]

54

### def recommend_books(book_name):
    book_id=np.where(book_pivot.index==book_name)[0][0]
    distances, suggestions=model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1), n_neighbors=6)
    
    for i in range(len(suggestions)):
            print(book_pivot.index[suggestions[i]])

In [152]:
suggestions

array([[237, 240, 238, 241, 184, 536]], dtype=int64)

In [151]:
suggestions[0]

array([237, 240, 238, 241, 184, 536], dtype=int64)

In [146]:
suggestions[0][0]

237

In [147]:
suggestions[0][1]

240

In [149]:
suggestions[0][2]

238

In [164]:
def recommend_books(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distances, suggestions = model.kneighbors(book_pivot.iloc[book_id, :].values.reshape(1, -1), n_neighbors=6)

    for i in range(len(suggestions[0])):
        if i!=0:
            print(book_pivot.index[suggestions[0][i]])
        

In [165]:
recommend_books('Animal Farm')

Exclusive
Jacob Have I Loved
Second Nature
Pleading Guilty
No Safe Place


In [166]:
recommend_books('Harry Potter and the Chamber of Secrets (Book 2)')

Harry Potter and the Prisoner of Azkaban (Book 3)
Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Sorcerer's Stone (Book 1)
Exclusive
The Cradle Will Fall


In [159]:
recommend_books('Exclusive')

The Cradle Will Fall
The Long Road Home
Jacob Have I Loved
No Safe Place
Eyes of a Child


In [160]:
recommend_books('The Cradle Will Fall')

Exclusive
The Long Road Home
Eyes of a Child
Jacob Have I Loved
No Safe Place


In [161]:
recommend_books('1984')

No Safe Place
A Civil Action
Foucault's Pendulum
Long After Midnight
Abduction
